on: [push]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    name: A job to run Java checkstyle
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
